import React, { useState } from 'react';
import Head from 'next/head';
import styles from '../../styles/Login.module.css'
import { useFormik } from 'formik';
import *as Yup from 'yup';
import { useSession, signIn, signOut } from "next-auth/client"

const initialValues = { name: "", password: "" }

const validationSchema = Yup.object({
    password: Yup.string(" ").required("این فیلد نباید خالی باشد").min(8, "رمز کوتاه است ").max(20),
    name: Yup.string().required("این فیلد نباید خالی باشد")
})

export default function Login() {
    const [showHide, setShowHide] = useState(false);

    const submitHandler = (value) => {
        console.log(value);
        signIn('credentials', { callbackUrl: 'false', password: 'password' , email: 'email'})
    }

    const formik = useFormik({
        initialValues,
        onSubmit: submitHandler,
        validationSchema,
        validateOnMount: true
    })

    return (
        <div className={styles.container}>
            <Head>
                <title>Login</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className={styles.totalBox}>
                <div className={styles.formContent}>
                    <div className={styles.title}>
                        <h3>سیستم بارگذاری سوالات</h3>
                    </div>
                    <form className={styles.formcontrol} onSubmit={formik.handleSubmit} >
                        <div className="form-input0">
                            <div className="input-icon">
                                <span className={styles.icon}> <i className="bi bi-person"></i> </span>
                            </div>
                            <input
                                onBlur={formik.handleBlur}
                                type="text"
                                name="name"
                                placeholder='پست الکترونیک / تلفن همراه'
                                onChange={formik.handleChange}
                                value={formik.values.name} />
                            {formik.errors.name && formik.touched.name && <div className={styles.passError}>{formik.errors.name}</div>}
                        </div>
                        <div className="form-input0">
                            <div className="input-icon">
                                <span className={styles.icon}> <i className="bi bi-lock"></i> </span></div>
                            <input
                                onBlur={formik.handleBlur}
                                value={formik.values.password}
                                type={showHide ? 'text' : 'password'}
                                onChange={formik.handleChange}
                                name="password"
                                placeholder='رمز عبور' />
                            <div className="input-icon-left">
                                <span className={styles.eyeContact}
                                    onClick={() => { setShowHide(!showHide) }} >{showHide ? <i className="bi bi-eye"></i> : <i className="bi bi-eye-slash"></i>}
                                </span>
                            </div>
                            {formik.errors.password && formik.touched.password && <div className={styles.passError}>{formik.errors.password}</div>}
                        </div>
                        <div className={styles.loginButton}>
                            <button type='submit' disabled={!formik.isValid} className={styles.submitButton} >ورود</button>
                            <p> <a href=''> رمز عبورتان را فراموش کردید؟ </a> </p>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    )
}



